import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const robotoRegular = localFont({
  src: "./fonts/Roboto-Regular.ttf",
  variable: '--font-roboto-regular',
  weight: '400'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoRegular.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
